CREATE TABLE `MA_APP_ICON_CATALOG` (
  `ID_ICON` INT(11) NOT NULL AUTO_INCREMENT,
  `ICON_CODE` VARCHAR(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  KEY `Key` (`ID_ICON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_CLINICAL_HISTORY_QUESTIONS` (
  `ID_QUIESTION` INT(11) NOT NULL AUTO_INCREMENT,
  `QUESTION_TEXT` VARCHAR(3200) NOT NULL,
  `ID_TYPE_QUESTION` INT(11) NOT NULL,
  `ID_CREATED_BY` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_QUIESTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_SPECIALTY_TYPE` (
  `ID_SPECIALTY_TYPE` INT(11) NOT NULL AUTO_INCREMENT,
  `SPECIALTY` VARCHAR(40) NOT NULL,
  KEY `Key` (`ID_SPECIALTY_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_NEWS_FAVORITE` (
  `ID_N_FAVORITE` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_NEWS` INT(11) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  KEY `Key` (`ID_N_FAVORITE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_PROSPECTS_FORM_QUESTIONS_TYPE` (
  `ID_TYPE_QUIESTION` INT(11) NOT NULL AUTO_INCREMENT,
  `QUESTION_ALIAS` VARCHAR(40) NOT NULL,
  `QUESTION_TYPE` VARCHAR(40) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_TYPE_QUIESTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_PROMOTIONS` (
  `ID_PROMOTION` INT(11) NOT NULL AUTO_INCREMENT,
  `P_TITLE` VARCHAR(40) NOT NULL,
  `P_DESCRIPTION` VARCHAR(250) NOT NULL,
  `P_TERMS_AND_CONDITIONS` VARCHAR(300) NOT NULL,
  `EXPIRATION_DATE` DATETIME NOT NULL,
  `VALID_DATE` DATETIME NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(40) NOT NULL,
  `ID_AVAILABLE_BRANCH` INT(11) NOT NULL,
  `ID_ICON` INT(11) NOT NULL,
  KEY `Key` (`ID_PROMOTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_APP_NAVIGATION` (
  `ID_ITEM` INT(11) NOT NULL AUTO_INCREMENT,
  `ITEM` VARCHAR(40) NOT NULL,
  `ID_APP_TYPE` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  KEY `Key` (`ID_ITEM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_APP_TYPE` (
  `ID_APP_TYPE` INT(11) NOT NULL AUTO_INCREMENT,
  `APP_NAME` VARCHAR(40) NOT NULL,
  FOREIGN KEY (`APP_NAME`) REFERENCES `MA_APP_NAVIGATION`(`ID_APP_TYPE`),
  KEY `Key` (`ID_APP_TYPE`, `APP_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_PROMOTIONS_USED` (
  `ID_PROMOTION` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USER` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_PROMOTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_NOTIFICATIONS` (
  `ID_NOTIFICATION` INT(11) NOT NULL AUTO_INCREMENT,
  `N_TITLE` VARCHAR(40) NOT NULL,
  `N_DESCRIPTION` VARCHAR(40) NOT NULL,
  `N_EXPIRATION_DATE` DATETIME NOT NULL,
  `ID_NOTIFICATION_CONCEPT` INT(11) NOT NULL,
  `ID_TYPE_NOTIFICATION` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_NOTIFICATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_BRANCH_SERVICE_LIST` (
  `ID_BRANCH_SERVICE_LIST` INT(11) NOT NULL AUTO_INCREMENT,
  `SERVICE_ITEM` VARCHAR(40) NOT NULL,
  `SERVICE_PRICE` VARCHAR(40) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_CREATED_BY` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_BRANCH_SERVICE_LIST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_STATE_RECORD` (
  `ID_STATE_RECORD` INT(11) NOT NULL AUTO_INCREMENT,
  `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `STATE_RECORD` VARCHAR(40) NOT NULL,
  `NOTE` VARCHAR(40) NOT NULL,
  FOREIGN KEY (`ID_STATE_RECORD`) REFERENCES `MA_BRANCH_SERVICE_LIST`(`ID_STATE_RECORD`),
  KEY `Key` (`ID_STATE_RECORD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_CLINICAL_HISTORY_ANSWERS` (
  `ID_QUIESTION` INT(11) NOT NULL AUTO_INCREMENT,
  `QUESTION_TEXT` VARCHAR(150) NOT NULL,
  `ID_TYPE_QUESTION` INT(11) NOT NULL,
  `ID_CREATED_BY` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_QUIESTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_BRANCHES` (
  `ID_BRANCH` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_BRANCH_SERVICE_LIST` INT(11) NOT NULL,
  `ID_RESPONSIBLE` INT(11) NOT NULL,
  `ST_D_K` VARCHAR(40) NOT NULL,
  `ST_P_K` VARCHAR(40) NOT NULL,
  `OWN_PAYMENTS` VARCHAR(40) NOT NULL,
  `DATA OF BRANCH…` VARCHAR(40) NOT NULL,
  KEY `Key` (`ID_BRANCH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_INVOICES` (
  `ID_INVOICE` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_QUOTE` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `FILE_URL` VARCHAR(160) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(40) NOT NULL,
  `DATE_UPDATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `Key` (`ID_INVOICE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_NOTIFICATION_TYPE` (
  `ID_NOTIFICATION_TYPE` INT(11) NOT NULL AUTO_INCREMENT,
  `N_TYPE` VARCHAR(40) NOT NULL,
  KEY `Key` (`ID_NOTIFICATION_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_USERS` (
  `ID_USER` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME_USER` VARCHAR(40) NOT NULL,
  `P_LASTNAME` VARCHAR(40) NOT NULL,
  `M_LASTNAME` VARCHAR(40) NOT NULL,
  `EMAIL` VARCHAR(40) NOT NULL,
  `PHONE_COUNTRY_PREFIX` VARCHAR(6) NOT NULL,
  `PHONE_NUMBER` VARCHAR(12) NOT NULL,
  `BIRTHDATE` DATETIME NOT NULL,
  `PROFILE_PICTURE` VARCHAR(40) NOT NULL,
  `PS_US` VARCHAR(40) NOT NULL,
  `GENDER` VARCHAR(12) NOT NULL,
  `E_C_PHONE_CONUTRY_PREFIX` VARCHAR(6) NOT NULL,
  `E_C_PHONE_NUMBER` VARCHAR(12) NOT NULL,
  `E_C_NAME` VARCHAR(40) NOT NULL,
  `PLACE_OF_BIRTH` DATETIME NOT NULL,
  `EMPLOYMENT` VARCHAR(40) NOT NULL,
  `MARITAL_STATUS` VARCHAR(40) NOT NULL,
  `DYNAMIC_KEY` VARCHAR(40) NOT NULL,
  `ID_BILLING_DATA` INT(11) NOT NULL,
  `ID_TYPE_USER` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_SUSPENDED_BY` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_TYPE_SOURCE_FILES` (
  `ID_TYPE_SOURCE_FILE` INT(11) NOT NULL AUTO_INCREMENT,
  `TYPE_SOURCE_FILE` VARCHAR(40) NOT NULL,
  KEY `Key` (`ID_TYPE_SOURCE_FILE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_NEWS` (
  `ID_NEWS` INT(11) NOT NULL AUTO_INCREMENT,
  `NEWS_TITLE` VARCHAR(40) NOT NULL,
  `NEWS_DESCRIPTION` VARCHAR(150) NOT NULL,
  `NEWS_IMG_FILE` VARCHAR(40) NOT NULL,
  `ID_NEWS_TYPE_USER` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_NEWS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_SERVICE_TYPE` (
  `ID_APPOINTMENT_TYPE` INT(11) NOT NULL AUTO_INCREMENT,
  `APPOINTMENT_TYPE` VARCHAR(40) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  KEY `Key` (`ID_APPOINTMENT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_APPOINTMENTS` (
  `ID_APPOINTMENT` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USER` INT(11) NOT NULL,
  `ID_BRANCH` INT(11) NOT NULL,
  `A_DATE` DATETIME NOT NULL,
  `A_TIME` VARCHAR(40) NOT NULL,
  `A_EMERGENCY` VARCHAR(120) NOT NULL,
  `A_PAYMENT_REQUIRED` VARCHAR(40) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_SERVICE_TYPE` INT(11) NOT NULL,
  `ID_DOCTOR` INT(11) NOT NULL,
  `ID_CREATED_BY` INT(11) NOT NULL,
  `DATE_RECORD` INT(11) NOT NULL,
  KEY `Key` (`ID_APPOINTMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_USER_BILLING_DATA` (
  `ID_BILLING_DATA_LIST` INT(11) NOT NULL AUTO_INCREMENT,
  `RFC` VARCHAR(40) NOT NULL,
  `BUSINESS_NAME` VARCHAR(40) NOT NULL,
  `ADDRESS` VARCHAR(160) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(120) NOT NULL,
  `FISCAL_FILE` VARCHAR(160) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `DATE_RECORD` INT(11) NOT NULL,
  KEY `Key` (`ID_BILLING_DATA_LIST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_TREATMENT_INDICATIONS` (
  `ID_TREATMENT` INT(11) NOT NULL AUTO_INCREMENT,
  `CUSTOM_TITLE` VARCHAR(80) NOT NULL,
  `CUSTOM_DESCRIPTION` VARCHAR(160) NOT NULL,
  `CUSTOM_SOURCE_FILE` VARCHAR(180) NOT NULL,
  `ID_TYPE_SOURCE_FILE` INT(11) NOT NULL,
  `ID_TREATMENT_INDICATIONS_CATALOG` INT(11) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  `ID_DOCTOR` INT(11) NOT NULL,
  `ID_BRANCH` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `EXPIRATION_DATE` DATETIME NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_TREATMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_CLINICAL_HISTORY_TEMPLATES` (
  `ID_CLINICAL_HISTORY_TEMPLATE` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_BRANCH_ACCESS` VARCHAR(40) NOT NULL,
  `QUESTION_ARRAY` VARCHAR(200) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_CREATED_BY` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `DATE_UPDATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `Key` (`ID_CLINICAL_HISTORY_TEMPLATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_TREATMENT_INDICATIONS_CATALOG` (
  `ID_T_I_CATALOG` INT(11) NOT NULL AUTO_INCREMENT,
  `T_I_TITLE` VARCHAR(40) NOT NULL,
  `T_I_DESCRIPTION` VARCHAR(40) NOT NULL,
  `SORUCE_FILE` VARCHAR(40) NOT NULL,
  `ID_TYPE_SOURCE_FILE` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  KEY `Key` (`ID_T_I_CATALOG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_PROSPECTS` (
  `ID_PROSPECT` INT(11) NOT NULL AUTO_INCREMENT,
  `PROSPECT_EMAIL` VARCHAR(120) NOT NULL,
  `PROSPECTS_QUESTIONS_ARRAY` VARCHAR(200) NOT NULL,
  `ID_SERVICE` INT(11) NOT NULL,
  `ID_BRANCH` INT(11) NOT NULL,
  `REFERRED_ORIGIN` VARCHAR(40) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_PROSPECT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_APP_SLIDER` (
  `ID_SLIDE` INT(11) NOT NULL AUTO_INCREMENT,
  `SLIDE_FILE` VARCHAR(160) NOT NULL,
  `SLIDE_TYPE` VARCHAR(120) NOT NULL,
  `SLIDE_POSITION` VARCHAR(10) NOT NULL,
  `ID_TYPE_USER` INT(11) NOT NULL,
  `CREATED_BY` VARCHAR(40) NOT NULL,
  `EXPIRATION_DATE` DATETIME NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_SLIDE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_DOCTORS` (
  `ID_DOCTOR` INT(11) NOT NULL AUTO_INCREMENT,
  `DOCTOR_NAME` VARCHAR(40) NOT NULL,
  `DOCTOR_P_LASTNAME` VARCHAR(40) NOT NULL,
  `DOCTOR_M_LASTNAME` VARCHAR(40) NOT NULL,
  `DOCTOR_EMAIL` VARCHAR(40) NOT NULL,
  `DOCTOR_PHONE` VARCHAR(40) NOT NULL,
  `DOCTOR_PHONE_ALTER` VARCHAR(40) NOT NULL,
  `PROFESSIONAL_ID_NUMBER` VARCHAR(40) NOT NULL,
  `ADDRESS` VARCHAR(40) NOT NULL,
  `PLACE_OF_BIRTH` VARCHAR(40) NOT NULL,
  `BIRTHDATE` VARCHAR(40) NOT NULL,
  `PS_DOCTOR` VARCHAR(40) NOT NULL,
  `GENDER` VARCHAR(40) NOT NULL,
  `E_C_PHONE_CONUTRY_PREFIX` VARCHAR(40) NOT NULL,
  `E_C_PHONE_NUMBER` VARCHAR(40) NOT NULL,
  `E_C_NAME` VARCHAR(40) NOT NULL,
  `ID_SPECIALTY` VARCHAR(40) NOT NULL,
  `DYNAMIC_KEY` VARCHAR(40) NOT NULL,
  `ID_TYPE_USER` INT(11) NOT NULL,
  `ID_SUSPENDED_BY` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `BRANCH_ARRAY` VARCHAR(40) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_DOCTOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_CLINICAL_HISTORY_FORMS` (
  `ID_CLINICAL_HISTORY` INT(11) NOT NULL AUTO_INCREMENT,
  `CLINICAL_HISTORY_NAME` VARCHAR(40) NOT NULL,
  `ID_TEMPLATE` VARCHAR(40) NOT NULL,
  `ANSWERS_ARRAY` VARCHAR(40) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  `ID_DOCTOR` INT(11) NOT NULL,
  `ID_BRANCH` INT(11) NOT NULL,
  `ID_CREATED_BY` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_CLINICAL_HISTORY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_BANK_TRANSFER` (
  `ID_BANK_TRANSFER` INT(11) NOT NULL AUTO_INCREMENT,
  `BANK_TRANSFER_REFERENCE` VARCHAR(40) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  `ID_BRANCH` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_BANK_TRANSFER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_NOTIFICATION_CONCEPT` (
  `ID_NOTIFICATION_CONCEPT` INT(11) NOT NULL AUTO_INCREMENT,
  `N_CONCEPT` VARCHAR(40) NOT NULL,
  KEY `Key` (`ID_NOTIFICATION_CONCEPT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_ADMINS` (
  `ID_ADMIN` INT(11) NOT NULL AUTO_INCREMENT,
  `ADMIN_NAME` VARCHAR(40) NOT NULL,
  `ADMIN_P_LASTNAME` VARCHAR(40) NOT NULL,
  `ADMIN_M_LASTNAME` VARCHAR(40) NOT NULL,
  `ADMIN_EMAIL` VARCHAR(40) NOT NULL,
  `ADMIN_PHONE` VARCHAR(40) NOT NULL,
  `ADMIN_PHONE_ALTER` VARCHAR(40) NOT NULL,
  `ADDRESS` VARCHAR(40) NOT NULL,
  `PLACE_OF_BIRTH` VARCHAR(40) NOT NULL,
  `BIRTHDATE` VARCHAR(40) NOT NULL,
  `PS_ADMIN` VARCHAR(40) NOT NULL,
  `GENDER` VARCHAR(40) NOT NULL,
  `DYNAMIC_KEY` VARCHAR(40) NOT NULL,
  `ID_TYPE_USER` INT(11) NOT NULL,
  `ID_SUSPENDED_BY` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `BRANCH_ARRAY` VARCHAR(40) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`ID_ADMIN`) REFERENCES `MA_BRANCH_SERVICE_LIST`(`ID_CREATED_BY`),
  KEY `Key` (`ID_ADMIN`),
  KEY `K` (`ID_SUSPENDED_BY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_OXXO_PAY` (
  `ID_OXXO_PAY` INT(11) NOT NULL AUTO_INCREMENT,
  `OXXO_PAY_REFERENCE` VARCHAR(40) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  `ID_BRANCH` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_OXXO_PAY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_PAYMENTS_TYP` (
  `ID_PAYMENT` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_WALLET_PAYMENT` INT(11) NOT NULL,
  `ID_BANK_TRANSFER` INT(11) NOT NULL,
  `ID_OXXO_PAY` INT(11) NOT NULL,
  `CASH` VARCHAR(40) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_PAYMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_TYPE_USER` (
  `ID_TYPE_USER` INT(11) NOT NULL AUTO_INCREMENT,
  `TYPE_USER` VARCHAR(40) NOT NULL,
  KEY `Key` (`ID_TYPE_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_GLOBAL_CONFIG` (
  `ID_APPOINTMENT_TYPE` INT(11) NOT NULL AUTO_INCREMENT,
  `BRANCH_PAYMENTS_ARRAY` VARCHAR(40) NOT NULL,
  `GLOBAL_PAYMENTS` VARCHAR(40) NOT NULL,
  `ST_D_K` VARCHAR(40) NOT NULL,
  `ST_P_K` VARCHAR(40) NOT NULL,
  KEY `Key` (`ID_APPOINTMENT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_PROSPECTS_FORM_QUESTIONS` (
  `ID_PROSPECT_FORM_QUIESTION` INT(11) NOT NULL AUTO_INCREMENT,
  `QUESTION_TEXT` VARCHAR(40) NOT NULL,
  `ID_TYPE_QUESTION` INT(11) NOT NULL,
  `ID_CREATED_BY` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_PROSPECT_FORM_QUIESTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_QUOTE_SERVICE_LIST` (
  `ID_QUOTE_S_LIST` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_QUOTE` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_SERVICE` INT(11) NOT NULL,
  `ID_PROMO` INT(11) NOT NULL,
  `PRICE` VARCHAR(40) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_QUOTE_S_LIST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_PAYMENTS` (
  `ID_PAYMENT` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_USER` INT(11) NOT NULL,
  `ID_QUOTE` INT(11) NOT NULL,
  `ID_PAYMENTS_TYPE` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_PAYMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_QUOTES` (
  `ID_QUOTE` INT(11) NOT NULL AUTO_INCREMENT,
  `QUOTE_ALIAS` VARCHAR(40) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_BRANCH` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_QUOTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_WALLET` (
  `ID_USER_WALLET` INT(11) NOT NULL AUTO_INCREMENT,
  `TOKEN` VARCHAR(40) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  `ID_BRANCH` INT(11) NOT NULL,
  `DATE_RECORD` INT(11) NOT NULL,
  KEY `Key` (`ID_USER_WALLET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_CLINICAL_HISTORY_TYPE_QUESTIONS` (
  `ID_TYPE_QUIESTION` INT(11) NOT NULL AUTO_INCREMENT,
  `QUESTION_ALIAS` VARCHAR(40) NOT NULL,
  `QUESTION_TYPE` VARCHAR(40) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_TYPE_QUIESTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SO_COMPANY_BUFFER` (
  `ID_COMPANY_BUFFER` INT(11) NOT NULL AUTO_INCREMENT,
  `DOCTOR_BUFFER` VARCHAR(40) NOT NULL,
  `BRANCH_BUFFER` VARCHAR(40) NOT NULL,
  `USER_BUFFER` VARCHAR(40) NOT NULL,
  `WA_REMINDERS_BUFFER` VARCHAR(40) NOT NULL,
  `SMS_REMINDERS_BUFFER` VARCHAR(40) NOT NULL,
  `NEWSLETTER_BUFFER` VARCHAR(40) NOT NULL,
  FOREIGN KEY (`ID_COMPANY_BUFFER`) REFERENCES `SO_COMPANY_CONFIG`(`ID_COMPANY`),
  KEY `Key` (`ID_COMPANY_BUFFER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SO_COMPANY_CONFIG` (
  `ID_COMPANY` INT(11) NOT NULL AUTO_INCREMENT,
  `MEMBERSHIP` VARCHAR(40) NOT NULL,
  `COMPANY_DATA` VARCHAR(150) NOT NULL,
  `API_KEY` VARCHAR(120) NOT NULL,
  `ID_STATE_RECORD` INT(11) NOT NULL,
  `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `Key` (`ID_COMPANY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SO_COMPANY_MODULES` (
  `ID_COMPANY_MODULES` INT(11) NOT NULL AUTO_INCREMENT,
  `HOME` VARCHAR(40) NOT NULL,
  `APPOINTMENTS` VARCHAR(40) NOT NULL,
  `PROMOS` VARCHAR(40) NOT NULL,
  `NEWS` VARCHAR(40) NOT NULL,
  `TREATMENTS` VARCHAR(40) NOT NULL,
  `CLINICAL_HISTORY` VARCHAR(40) NOT NULL,
  `QUOTES` VARCHAR(40) NOT NULL,
  `PUSH_NOTIFICATIONS` VARCHAR(40) NOT NULL,
  `WA_NOTIFICATIONS` VARCHAR(40) NOT NULL,
  `NEWSLETTERS` VARCHAR(40) NOT NULL,
  FOREIGN KEY (`ID_COMPANY_MODULES`) REFERENCES `SO_COMPANY_CONFIG`(`ID_COMPANY`),
  KEY `Key` (`ID_COMPANY_MODULES`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `keys` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `key` VARCHAR(40) NOT NULL,
  `level` INT(2) NOT NULL,
  `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
  `is_private_key` TINYINT(1)  NOT NULL DEFAULT '0',
  `ip_addresses` TEXT NULL DEFAULT NULL,
  `date_created` INT(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(255) NOT NULL,
  `method` VARCHAR(6) NOT NULL,
  `params` TEXT DEFAULT NULL,
  `api_key` VARCHAR(40) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `time` INT(11) NOT NULL,
  `rtime` FLOAT DEFAULT NULL,
  `authorized` VARCHAR(1) NOT NULL,
  `response_code` smallint(3) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MA_AUTH` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT, 
  `ID_USER` INT(11) NOT NULL,
  `EMAIL` VARCHAR(80) NOT NULL, 
  `PICCTURE` VARCHAR(255) NOT NULL,
  `TYPE` VARCHAR(60) NOT NULL, 
  `SALT` VARCHAR(64) NOT NULL, 
  `PASSWORD` VARCHAR(200) NOT NULL, 
  `LAST_LOGIN` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `IP` VARCHAR(15) NOT NULL, 
  PRIMARY KEY (`ID`), 
  UNIQUE `EMAIL` (`EMAIL`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;